#checks if its working
name: Python Validation

on: [push, pull_request]

jobs:
  validate_python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    # - name: Debugging - List files in workspace
    #   run: ls -l

    # - name: Debugging - Print current directory
    #   run: pwd

    - name: Run Python script for books
      run: |
          cd pythonproblems/books
          python books.py
         
          
    - name: Run Python script for datecheck
      run: |
          cd pythonproblems/datecheck
          python  date.py "2024-03-28"
          
    - name: Run Python script for emailcheck
      run: |
          cd pythonproblems/emailcheck
          python  email.py user@example.com

    # - name: Run Python testscript for boooktest
    #   run: |
    #       python -m unittest pythonproblems/tests/booktest.py
    - name: Run Python testscript for booktest
      run: |
          python -m unittest pythonproblems/tests/booktest.py
          
    - name: Run Python testscript for datecheck
      run: |
          python -m unittest pythonproblems/tests/datetest.py
          
    - name: Run Python testscript for emailcheck
      run: |
          python -m unittest pythonproblems/tests/emailtest.py
     
