name: Python Validation

on: [push, pull_request]

jobs:
  validate_python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    # - name: Debugging - List files in workspace
    #   run: ls -l

    # - name: Debugging - Print current directory
    #   run: pwd

    - name: Run Python script for books
      run: |
          cd pythonproblems/books
          python books.py books.json

    # - name: Run Python script for date
    #   run:  python pythonproblems/datecheck/date.py

    # - name: Run Python script for email
    #   run: python pythonproblems/emailcheck/email.py

    # - name: Run unit tests
    #   run: python -m unittest discover
